### ISSUE TITLE
php version support for 8.1

### ISSUE THREAD

**Issue by nihiels** [digitalprint/magento-2-printess-designer#1]
Thanks a lot for publishing this extension!
I tried to install it to my blank example store and faced a requirements issue:

```
Package digitalprint/magento-2-printess-designer has requirements incompati  
  ble with your PHP version, PHP extensions and Composer version:              
    - digitalprint/magento-2-printess-designer v1.5.11 requires php ~7.3.0||~  
  7.4.0 which does not match your installed version 8.1.8. 
```
Is there a chance to change this requirement? It took me quite a while to setup the magento shop :/

Cheers

Nils

**Comment by watermusic** [comment]
So far, an update to a new version is not yet planned. 
We would like to upgrade our Magento store to the latest Magento version at the beginning of next year.
Then we will also make the printess extension here php 8.1 capable.
It may also already be that it is 8.1 capable, only we have not tested this yet.
But you are welcome to start a pull request and set the PHP version there to 8.1 and try it out. It could already be that it works.

**Comment by nihiels** [comment]
It seems to work with version 8.1. Or maybe not :/ At least I got no errors so far.
I tried to link a product to the printess business card template:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/6154792/178497949-e5fa7878-f004-4e6b-9f36-c11a58342b54.png">

I added the fields as customizable options.

Now looking at the pruduct, the add to basket button is still active.
Is there anything you can tell me, where to look at or what would be a good start template to see it in action?

**Comment by sweikert** [comment]
Do you have other extensions installed? This could be a problem if these extensions overwrite default templates.

**Comment by nihiels** [comment]
No, it's blank installation with sample data and no extensions at all:
https://magento.pfeifenberger.net/businesscard.html

**Comment by sweikert** [comment]
Maybe a problem with the newer Magento version. 

I just tried to open the designer manually in the browser for testing but the page does not open either?

https://magento.pfeifenberger.net/designer/page/view/?sku=businesscard

**Comment by AlexanderOser** [comment]
I had the same issues. On my side it seemed to be cashing issues that are not fixed by clearing the cache. Restarting my docker container helped and The Configure button was shown instead of the add to basket and the redirect to the edit page also worked (threw 404 before).
