### ISSUE TITLE
Error: Class "Printess\Api\PrintessApiClient" not found in 

### ISSUE THREAD

**Issue by nihiels** [digitalprint/magento-2-printess-designer#2]
Finally I managed it to get a Printess template orderable in Magento But when downloading it, I get the following error:

main.CRITICAL: Error: Class "Printess\Api\PrintessApiClient" not found in /magento/app/code/Digitalprint/PrintessDesigner/Controller/Adminhtml/Download/Index.php:141

I can't find this PrintessApiClient. Could you help me out here?

Cheers

Nils

**Comment by nihiels** [comment]
Sorry, my bad. I thought I did but...

**Comment by sweikert** [comment]
No problem, but there is also a problem with the cachekey. The bugfix will be in the next release.

https://github.com/digitalprint/magento-2-printess-designer/commit/0fe42ca152b35ae23321422a4a5980406222720e
