### ISSUE TITLE
Exception in CheckoutCartAdd Observer

### ISSUE THREAD

**Issue by mansgustafsson** [digitalprint/magento-2-printess-designer#6]
Also, and my PHP skills are way to small to know the reason for this issue, but I got an exception when trying to add products (non-printess-products) to the basket. This is on 2.4.5-p1 with PHP 7.4x. I had to make the following change in the CheckoutCartAdd observer:

//$params = json_decode($this->request->getContent(), true, 512, JSON_THROW_ON_ERROR);
$params = json_decode($this->request->getContent(), true);

**Comment by sweikert** [comment]
The getContent function return an empty string for non-printess-products. I have refactored the json handling. Fixed in [4a3976a](https://github.com/digitalprint/magento-2-printess-designer/commit/4a3976afb0b127490d99f733348ffa12f4f7b5c4)
